function createCorePicture(cdata1, x_aspectRatio)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 03-Mar-2015 10:29:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Visible','off','Parent',figure1,'Layer','top',...
    'YDir','reverse',...
    'PlotBoxAspectRatio',[x_aspectRatio 1 0.464223385689354],...
    'Units','pixels');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 416.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 61537.5]);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1);

