function corePlugPorosityPermXPLOT(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 19-Feb-2015 19:39:36

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','YScale','log',...
    'Position',[0.13 0.0586319218241042 0.76242745930644 0.866368078175896]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[2 25]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 100]);
hold(axes1,'on');

% Create ylabel
ylabel({'Permeablity (md)'});

% Create xlabel
xlabel({'Porosity %'});

% Create title
title({'Core Plug Porsity/Permeability XPLOT'},'FontSize',14);

% Create semilogy
semilogy(X1,Y1,'DisplayName','','Marker','+','LineStyle','none');

