function createPE_DensityXPLOT(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 19-Feb-2015 17:37:47

% Create figure
figure1 = figure;

% Create axes


axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','YDir','reverse',...
    'Position',[0.13 0.160775370581528 0.455987261146497 0.800763090956933]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 6]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[1.9 3.0]);
box(axes1,'on');
hold(axes1,'on');
% Create ylabel
ylabel({'Density (g/cc)'});

% Create xlabel
xlabel({'PE (B/e)'});

% Create title
title({'PEF/Density XPLOT'});
%Create Annotations
%sandlineX = [2.65 2.49 2.331 2.18 1.9];
%sandlineY = [1.8 1.7 1.65 1.6 1.5];
%plot(sandlineY,sandlineX,'DisplayName','CleanSSLine','Marker','+','LineStyle','-');
% Create plot
plot(X1,Y1,'DisplayName','','Marker','+','LineStyle','none');

