function createTh_K_Xplot(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 23-Feb-2015 09:58:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'Position',[0.13 0.11 0.495845737483085 0.815]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 5]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 25]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel({'Thorium (ppm)'});

% Create xlabel
xlabel({'Potassium (%)'});

% Create title
title({'Thorium/Potassium Lithology Cross-Plot'});

% Create plot
plot(X1,Y1,'DisplayName','','Marker','+','LineStyle','none');

