function createSaturationPickettPlot(X1, Y1, S1, C1)
%CREATEFIGURE(X1, Y1, S1, C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 23-Feb-2015 11:30:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','XScale','log',...
    'Position',[0.119079837618403 0.0444697833523375 0.774695534506089 0.930444697833524]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[1 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 30]);
hold(axes1,'on');

% Create ylabel
ylabel({'Core Plug Porosity (%)'});

% Create xlabel
xlabel({'Deep Resistivity (ohm-m)'});

% Create title
title({'Core Plug Porosity vs Log Resistivity vs Plug Saturation'});

% Create scatter
scatter(X1,Y1,S1,C1);

% Create textbox
annotation(figure1,'textbox',...
    [0.137671177266577 0.923603192702395 0.191828146143437 0.0136830102622577],...
    'String',{'Larger Marker size = Higher Measured Plug Oil Saturation'},...
    'FitBoxToText','off');

