function  createNeutronDensityXPLOT( X1, Y1, faciesCode)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 19-Feb-2015 15:55:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YDir','reverse');
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 0.45]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[2 2.8]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName',char(faciesCode),'Marker','+','LineStyle','none');

% Create legend
%legend1 = legend(axes1,'show');
%set(legend1,'FontSize',9);

