function create4DPEF_Density_XPLOT(X1, Y1, S1, C1, theTitle)
%CREATEFIGURE(X1, Y1, S1, C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 23-Feb-2015 13:50:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YDir','reverse');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 5]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[2.1 2.9]);
hold(axes1,'on');

% Create ylabel
ylabel({'Formation Density (g/cc)'});

% Create xlabel
xlabel({'Photoelectric Factor (b/e)'});

% Create title
title(theTitle);

% Create scatter
scatter(X1,Y1,S1,C1);

