function createPickettPlot(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 23-Feb-2015 10:19:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','XScale','log',...
    'Position',[0.13 0.11 0.41871447902571 0.815]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0.5 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0.01 0.5]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel({'Porosity (%)'});

% Create xlabel
xlabel({'Deep Resistivity (ohm-m)'});

% Create title
title({'Porosity versus Formation Resistivity (Pickett Plot)'});

% Create semilogx
semilogx(X1,Y1,'DisplayName','','Marker','+','LineStyle','none');

