function plugLuminosityXPLOT(X1, Y1)
%CREATEFIGURE(X1, Y1, S1, C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 12-Mar-2015 08:53:11

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[29 220]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 50]);
grid(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Plug Oil Saturation %');

% Create xlabel
xlabel('Luminosity Index');

% Create title
%title('Mudstone Luminosity vs Plug Oil Saturation');

% Create scatter
scatter(X1,Y1);

