function [rawData1] = importPNG(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 02-Mar-2015 11:15:13

% Import the file
rawData1 = importdata(fileToRead1);

% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.
%[~,name] = fileparts(fileToRead1);
%newData1.(genvarname(name)) = rawData1; %#ok<DEPGENAM>

% Create new variables in the base workspace from those fields.
%vars = fieldnames(newData1);
%for i = 1:length(vars)
%    assignin('base', vars{i}, newData1.(vars{i}));
%end

