function CorePlugInputs = importCorePlugs(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   X24RCOREPLUGINPUTS = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   X24RCOREPLUGINPUTS = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   X24RCorePlugInputs = importfile('322X-24RCorePlugInputs.txt', 4, 137);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/03/11 07:53:25

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 4;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: text (%s)
%   column17: text (%s)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: text (%s)
%	column22: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%f%f%f%f%f%f%f%f%f%f%f%f%s%s%f%f%f%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataArray([4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 19, 20]) = cellfun(@(x) num2cell(x), dataArray([4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 19, 20]), 'UniformOutput', false);
CorePlugInputs = [dataArray{1:end-1}];
