function [MD,Gamma1,RHOB1,SP1,XNPHIS1,PEF1,RD1,RS1,GammaNOUr,GammaK,GammaTh,GammaU,XMINV,XMNOR] = importStandardLogsv2(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [MD,GAMMA1,RHOB1,SP1,XNPHIS1,PEF1,RD1,RS1,GAMMANOUR,GAMMAK,GAMMATH,GAMMAU,XMINV,XMNOR]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [MD,GAMMA1,RHOB1,SP1,XNPHIS1,PEF1,RD1,RS1,GAMMANOUR,GAMMAK,GAMMATH,GAMMAU,XMINV,XMNOR]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [MD,Gamma1,RHOB1,SP1,XNPHIS1,PEF1,RD1,RS1,GammaNOUr,GammaK,GammaTh,GammaU,XMINV,XMNOR]
%   = importfile('BasicLogInputs.txt',2, 29982);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/02/23 07:36:40

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: text (%s)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%s%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
MD = dataArray{:, 1};
Gamma1 = dataArray{:, 2};
RHOB1 = dataArray{:, 3};
SP1 = dataArray{:, 4};
XNPHIS1 = dataArray{:, 5};
PEF1 = dataArray{:, 6};
RD1 = dataArray{:, 7};
RS1 = dataArray{:, 8};
GammaNOUr = dataArray{:, 9};
GammaK = dataArray{:, 10};
GammaTh = dataArray{:, 11};
GammaU = dataArray{:, 12};
XMINV = dataArray{:, 13};
XMNOR = dataArray{:, 14};


