function bedThicknessDist(data1, titleString)
%CREATEFIGURE(DATA1)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 13-Mar-2015 14:19:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','XScale','log');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0.01 10]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 15000]);
box(axes1,'on');

% Create ylabel
ylabel(['Bed Counts';'          '],'FontSize',11);

% Create xlabel
xlabel('Bed Thickness (ft)','FontSize',11);

% Create title
title( titleString,'FontSize',11);

% Create histogram
histogram(data1,'Parent',axes1,'EdgeColor',[0 0 0],'FaceColor','auto',...
    'Normalization','count',...
    'BinMethod','auto');

